In [10]:
import numpy as np

In [2]:
# Задание 1
# Импортируйте библиотеку Numpy и дайте ей псевдоним np.
# Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
# Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. 
# Будем считать, что каждый столбец - это признак, а строка - наблюдение. 
# Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. 
# Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [17]:
a = np.array ([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])
a.shape

(5, 2)

In [19]:
b=a[0:,:1]
print (b)

[[1]
 [2]
 [3]
 [3]
 [1]]


In [20]:
mean_b=np.mean(b)
print (mean_b)

2.0


In [25]:
c=a[0:,1:]
print (c)

[[ 6]
 [ 8]
 [11]
 [10]
 [ 7]]


In [26]:
mean_c=np.mean(c)
print (mean_c)

8.4


In [27]:
mean_a=mean_b,mean_c
print(mean_a)

(2.0, 8.4)


In [ ]:
# Задание 2
# Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. 
# Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.


In [28]:
a_centered=np.subtract(a,mean_a)
print (a_centered)

[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


In [30]:
# Задание 3
# Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. 
# Затем поделите a_centered_sp на N-1, где N - число наблюдений.
a_centered_sp=a_centered[0:,:1]*a_centered[0:,1:]
print (a_centered_sp)


[[ 2.4]
 [-0. ]
 [ 2.6]
 [ 1.6]
 [ 1.4]]


In [38]:
x=a_centered_sp.shape[0]-1
print(x)

4


In [39]:
y=a_centered_sp/x
print (y)    

[[ 0.6 ]
 [-0.  ]
 [ 0.65]
 [ 0.4 ]
 [ 0.35]]
